### ISSUE TITLE
Create `V` template

### ISSUE THREAD

**Issue by shiipou** [lenra-io/template-v#2]
Template must run the counter app in [V](https://github.com/vlang/v)

We choose to use the same app for each template to help new developers to see how to implement they app when switching languages.

## Tasks to do:

Setting up the default app:
- [x] Create `handle_manifest` function
- [x] Create `handle_widget` function
- [x] #4
- [x] #5
- [x] Create `get_document` function
- [x] Create `create_document` function
- [x] Create `update_document` function
- [x] Create `delete_document` function
- [x] Create `execute_query` function

Setting up widgets:
- [x] root
- [x] #3
- [x] menu
- [x] counter
- [x] loading
- [x] root

Setting up listeners:
- [x] #6
- [x] #7
- [x] #8

## Config lenra with Dofigen
- [x] Add `/lenra.yml` Dofigen file for template configuration
